# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac7fe1b4748e859e1818fc2936e647de32a5de905a666de8bd6f248d90736e8fd65dfa7162a6fdda35dfb85ed7751715ee604acb8a76cd23751f75c2b634ee1a

test:
  secret_key_base: 2499003bf8f1748a85491161ac6bafc01bb27a42a27001692d456d504852c841f7eb2599552837f2ebca787bd562455e083249874b939d434197790aafb5c4c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
